TRAINING_EXAMPLE_DEPTH = 10
#TRAINING_EXAMPLE_C1C2C3_GENERATION_STEP = 1
#TRAINING_EXAMPLE_C1C2C3_GENERATION_START_INDEX = 1
#TRAINING_EXAMPLE_C1C2C3_GENERATION_END_INDEX = 9
TRAINING_EXAMPLE_C1C2C3_GENERATION_LIST = [1,2,3,4,5,6,7,8]
TRAINING_EXAMPLE_C0_GENERATION_LIST = [-8,-6,-4,-2]
TRAINING_EXAMPLE_C0_GENERATION_FRAME_INTERVAL = 240
TRAINING_EXAMPLE_HEIGHT = 240
TRAINING_EXAMPLE_WIDTH = 135

TRAINING_BATCH_SIZE = 16



'''
For previous depth=5 setting:

TRAINING_EXAMPLE_DEPTH = 5
TRAINING_EXAMPLE_C1C2C3_GENERATION_STEP = 1
TRAINING_EXAMPLE_C1C2C3_GENERATION_START_INDEX = 0
TRAINING_EXAMPLE_C1C2C3_GENERATION_END_INDEX = 5
TRAINING_EXAMPLE_C0_GENERATION_FRAME_INTERVAL = 120
TRAINING_EXAMPLE_HEIGHT = 240
TRAINING_EXAMPLE_WIDTH = 135

TRAINING_BATCH_SIZE = 16
'''